class Beacons():
    print("Stations1")
    import os
    import sqlite3
    import re
    
    def __init__(self):
        super().__init__()

    #----------------------------------------
    # Import Beacon data to database
    # Data is in 2 html files available
    # Take each html file and call subroutine
    # to read data into database
    #----------------------------------------
    def ImpBeacon(self):
		# Get Working Path
        strPath = Beacons.os.getcwd()
        
        # DB
        dbStations = "beacons.db"
        
        # Input1
        dbMode = "overwrite"
        #strFileIn = "G3USF's Worldwide List of HF Beacons.htm"
        strFileIn = "hf.htm"
        Beacons.ReadG3USF(self, strFileIn, dbStations, dbMode)
        
        # Input2
        dbMode = "append"
        #strFileIn = "G3USF's Worldwide List of 50MHz Beacons.htm"
        strFileIn = "50.htm"
        Beacons.ReadG3USF(self, strFileIn, dbStations, dbMode)
    
    #-------------------------------------------
    # Read html file and import data to database
    #-------------------------------------------
    def ReadG3USF(self, strFileIn, dbStations, dbMode):
        
        fobjFileIn = open(strFileIn, "r")
        fobjFileOut = open("beacon_list.txt", "w")
        conn = Beacons.sqlite3.connect(dbStations)
        curs = conn.cursor()
        
        #------------------------------------------------------
        # Dictionary to translate call to country and continent
        #------------------------------------------------------
        
        dicCountry = {
        "1A":["Sovereign Military Order of Malta","EU"],
        "1B":["Cyprus","EU"],
        "1S":["Spratly Is","OZ"],
        "2E":["England (Novices)","EU"],
        "2D":["Isle Of Man (Novices)","EU"],
        "2I":["Northern Ireland (Novices)","EU"],
        "2J":["Jersey (Novices)","EU"],
        "2M":["Scotland (Novices)","EU"],
        "2U":["Guernsey & Dependencies (Novices)","EU"],
        "2W":["Wales (Novices)","EU"],
        "3A":["Monaco","EU"],
        "3B":["Mauritius","AF"],
        "3B6":["Agalega","OZ"],
        "3B7":["Agalega","OZ"],
        "3B8":["Mauritius","OZ"],
        "3B9":["Rodriguez Is","AF"],
        "3C":["Equatorial Guinea","AF"],
        "3C0":["Annobon","AF"],
        "3D2":["Conway Reef","OZ"],
        "3D2":["Fiji Is","OZ"],
        "3D2":["Rotuma","OZ"],
        "3D2/C":["Conway Reef","OZ"],
        "3D2/F":["Fiji Islands","OZ"],
        "3D2/R":["Rotuma","OZ"],
        "3D6":["Swaziland","AF"],
        "3DA0":["Swaziland","AF"],
        "3G":["Chile","SA"],
        "3V":["Tunisia","AF"],
        "3W":["Vietnam","AS"],
        "3X":["Guinea","AF"],
        "3Y":["Bouvet Is","AF"],
        "3Y":["Peter Is","SA"],
        "3Y/B":["Bouvet","AF"],
        "3Y/P":["Peter Is","SA"],
        "3Z":["Poland","EU"],
        "4A":["Mexico","NA"],
        "4B":["Mexico","NA"],
        "4C":["Mexico","NA"],
        "4D":["Philippines","AS"],
        "4F":["Philippines","AS"],
        "4I":["Philippines","AS"],
        "4J":["Azerbaijan","AS"],
        "4J1":["Malyj Vysotskij","EU"],
        "4K":["Russian Polar Sta","AS"],
        "4L":["Georgia","AS"],
        "4M":["Venezuela","SA"],
        "4N1":["Yugoslavia (Regular)","EU"],
        "4N4":["Bosnia Herzegovina","EU"],
        "4N5":["Macedonia","EU"],
        "4N6":["Yugoslavia (Regular)","EU"],
        "4N7":["Yugoslavia (Regular)","EU"],
        "4N8":["Yugoslavia (Regular)","EU"],
        "4N9":["Yugoslavia (Reserved)","EU"],
        "4N0":["Yugoslavia (Reserved)","EU"],
        "4O1":["Yugoslavia (Special)","EU"],
        "4O4":["Bosnia Herzegovina","EU"],
        "4O5":["Macedonia","EU"],
        "4O6":["Yugoslavia (Special)","EU"],
        "4O7":["Yugoslavia (Special)","EU"],
        "4O8":["Yugoslavia (Special)","EU"],
        "4O9":["Yugoslavia (Reserved)","EU"],
        "4O0":["Yugoslavia (Reserved)","EU"],
        "4P":["Sri Lanka","AS"],
        "4Q":["Sri Lanka","AS"],
        "4R":["Sri Lanka","AS"],
        "4S":["Sri Lanka","AS"],
        "4T":["Peru","SA"],
        "4U":["I.T.U. Geneva","EU"],
        "4U":["U.N. N.Y.","NA"],
        "4U1VIC":["Vienna Int. Congress Center.","EU"],
        "4V":["Haiti","NA"],
        "4W":["Yemen","AS"],
        "4X":["Israel","AS"],
        "4Z":["Israel","AS"],
        "5A":["Libya","AF"],
        "5B":["Cyprus","EU"],
        "5C":["Morocco","AF"],
        "5D":["Morocco","AF"],
        "5H":["Tanzania","AF"],
        "5I":["Tanzania","AF"],
        "5J":["Columbia","SA"],
        "5K":["Columbia","SA"],
        "5L":["Liberia","AF"],
        "5N":["Nigeria","AF"],
        "5O":["Nigeria","AF"],
        "5R":["Malagasy Rep","AF"],
        "5S":["Malagasy Rep","AF"],
        "5T":["Mauritania","AF"],
        "5U":["Niger","AF"],
        "5V":["Togo","AF"],
        "5W":["Western Samoa","AF"],
        "5X":["Uganda","AF"],
        "5Y":["Kenya","AF"],
        "5Z":["Kenya","AF"],
        "6D":["Mexico","Na"],
        "6E":["Mexico","NA"],
        "6G":["Mexico","NA"],
        "6I":["Mexico","NA"],
        "6K":["South Korea","AS"],
        "6O":["Somalia","AF"],
        "6T":["Sudan","AF"],
        "6V":["Senegal","AF"],
        "6W":["Senegal","AF"],
        "6Y":["Jamaica","NA"],
        "7J":["Japan","AS"],
        "7K":["Japan","AS"],
        "7L":["Japan","AS"],
        "7M":["Japan","AS"],
        "7N":["Japan","AS"],
        "7O":["Yemen Peo Rep","AS"],
        "7P":["Lesotho","AF"],
        "7Q":["Malawi","AF"],
        "7S":["Sweden","EU"],
        "7T":["Algeria","AF"],
        "7U":["Algeria","AF"],
        "7V":["Algeria","AF"],
        "7W":["Algeria","AF"],
        "7X":["Algeria","AF"],
        "7Y":["Algeria","AF"],
        "7Z":["Saudi Arabia","AS"],
        "8A":["Indonesia","AS"],
        "8B":["Indonesia","AS"],
        "8C":["Indonesia","AS"],
        "8D":["Indonesia","AS"],
        "8E":["Indonesia","AS"],
        "8F":["Indonesia","AS"],
        "8G":["Indonesia","AS"],
        "8H":["Indonesia","AS"],
        "8I":["Indonesia","AS"],
        "8J":["Japan","AS"],
        "8O":["Botswana","AF"],
        "8P":["Barbados","NA"],
        "8Q":["Maldive Is","AS"],
        "8R":["Guyana","AS"],
        "8S":["Sweden","EU"],
        "8T":["India","AS"],
        "8T4":["Andaman Is",""],
        "8T7":["Laccadive Is",""],
        "8U":["India","AS"],
        "8U4":["Andaman Is",""],
        "8U7":["Laccadive Is",""],
        "8V":["India","AS"],
        "8V4":["Andaman Is",""],
        "8V7":["Laccadive Is",""],
        "8W":["India","AS"],
        "8W4":["Andaman Is",""],
        "8W7":["Laccadive Is",""],
        "8Z":["Saudi Arabia","AS"],
        "9A":["Croatia","EU"],
        "9D":["Iran","AS"],
        "9E":["Ethiopia","AF"],
        "9F":["Ethiopia","AF"],
        "9G":["Ghana","AF"],
        "9H":["Malta","EU"],
        "9I":["Zambia","AF"],
        "9J":["Zambia","AF"],
        "9K":["Kuwait","AS"],
        "9L":["Sierra Leone","AF"],
        "9M0":["Spratly Is",""],
        "9M":["Malaysia","AS"],
        "9M2":["West Malaysia","AS"],
        "9M4":["West Malaysia","AS"],
        "9M6":["East Malaysia","AS"],
        "9M8":["East Malaysia","AS"],
        "9N":["Nepal","AS"],
        "9Q":["Zaire","AF"],
        "9R":["Zaire","AF"],
        "9T":["Zaire ","AF"],
        "9U":["Burundi","AS"],
        "9V":["Singapore","AS"],
        "9X":["Rwanda","AF"],
        "9Y":["Trinidad","SA"],
        "9Z":["Trinidad","SA"],
        "A1":["Abu Ail","AF"],
        "A15":["Abu Ail","AF"],
        "A2":["Botswana","AF"],
        "A3":["Tonga","AF"],
        "A4":["Oman","AS"],
        "A5":["Bhutan","AS"],
        "A51":["Bhutan","AS"],
        "A6":["Emirites","AS"],
        "A7":["Qatar","AS"],
        "A8":["Liberia","AF"],
        "A9":["Bahrain","AS"],
        "AA-AK":["USA","NA"],
        "AA":["USA","NA"],
        "AB":["USA","NA"],
        "AC":["USA","NA"],
        "AD":["USA","NA"],
        "AE":["USA","NA"],
        "AF":["USA","NA"],
        "AG":["USA","NA"],
        "AH":["USA","NA"],
        "AI":["USA","NA"],
        "AJ":["USA","NA"],
        "AK":["USA","NA"],
        "AC6":["West Carolines",""],
        "AH0":["Mariana Is",""],
        "AH1":["Baker Howland",""],
        "AH2":["Guam",""],
        "AH3":["Johnston Is",""],
        "AH4":["Midway Is",""],
        "AH5":["Palmyra Is",""],
        "AH5K":["Kingman Reef",""],
        "AH6":["Hawaii",""],
        "AH7K":["Kure Is",""],
        "AH8":["American Samoa",""],
        "AH9":["Wake Is",""],
        "AL":["USA Alaska","NA"],
        "AM":["Spain","EU"],
        "AM6":["Balearic Is",""],
        "AM8":["Canary Is","AF"],
        "AM9":["Ceuta-Melilla","AF"],
        "AN":["Spain","EU"],
        "AN6":["Balearic Is","EU"],
        "AN8":["Canary Is","AF"],
        "AN9":["Ceuta-Melilla","AF"],
        "AO":["Spain","EU"],
        "AO6":["Balearic Is","EU"],
        "AO8":["Canary Is","AF"],
        "AO9":["Ceuta-Melilla","AF"],
        "AP":["Pakistan","AS"],
        "AQ":["Pakistan","AS"],
        "AR":["Pakistan","AS"],
        "AS":["Pakistan","AS"],
        "AT":["India","AS"],
        "AT4":["Andaman Is",""],
        "AT7":["Laccadive Is",""],
        "AU":["India","AS"],
        "AU4":["Andaman Is",""],
        "AU7":["Laccadive Is",""],
        "AV":["India","AS"],
        "AV4":["Andaman Is",""],
        "AV7":["Laccadive Is",""],
        "AW":["India","AS"],
        "AW4":["Andaman Is",""],
        "AW7":["Laccadive Is",""],
        "AX":["Australia","AU"],
        "AY":["Argentina","SA"],
        "AZ":["Argentina","SA"],
        "BA-BU":["China","AS"],
        "BA":["China","AS"],
        "BB":["China","AS"],
        "BC":["China","AS"],
        "BD":["China","AS"],
        "BE":["China","AS"],
        "BF":["China","AS"],
        "BG":["China","AS"],
        "BH":["China","AS"],
        "BI":["China","AS"],
        "BJ":["China","AS"],
        "BK":["China","AS"],
        "BL":["China","AS"],
        "BM":["China","AS"],
        "BN":["China","AS"],
        "BO":["China","AS"],
        "BP":["China","AS"],
        "BQ":["China","AS"],
        "BR":["China","AS"],
        "BS":["China","AS"],
        "BT":["China","AS"],
        "BU":["China","AS"],
        "BV":["Taiwan","AS"],
        "BW":["China","AS"],
        "BX":["China","AS"],
        "BY":["China","AS"],
        "BZ":["China","AS"],
        "C2":["Nauru","SA"],
        "C3":["Andorra","EU"],
        "C4":["Cyprus","EU"],
        "C5":["Gambia","AF"],
        "C6":["Bahamas","SA"],
        "C8":["Mozambique","AF"],
        "C9":["Mozambique","AF"],
        "CA":["Chile","SA"],
        "CB":["Chile","SA"],
        "CC":["Chile","SA"],
        "CD":["Chile","SA"],
        "CE":["Chile","SA"],
        "CE1-CE8":["Chile","SA"],
        "CE9":["Antarctica","AN"],
        "CE0A":["Easter Island","OZ"],
        "CE0E":["Easter Island","OZ"],
        "CE0F":["Easter Island","OZ"],
        "CE0I":["Juan Fernandez ",""],
        "CE0X":["San Felix",""],
        "CE0Y":["Easter Island","OZ"],
        "CE0Z":["Juan Fernandez",""],
        "CF":["Canada","NA"],
        "CG":["Canada","NA"],
        "CH":["Canada","NA"],
        "CI":["Canada","NA"],
        "CJ":["Canada","NA"],
        "CK":["Canada","NA"],
        "CL":["Cuba","NA"],
        "CM":["Cuba","NA"],
        "CN":["Morocco","AF"],
        "CO":["Cuba","NA"],
        "CP":["Bolivia","SA"],
        "CQ":["Portugal","EU"],
        "CQ3":["Madeira Is",""],
        "CQ9":["Madeira Is",""],
        "CR":["Portugal","EU"],
        "CR3":["Madeira Is",""],
        "CR9":["Madeira Is",""],
        "CS":["Portugal","EU"],
        "CT":["Portugal","EU"],
        "CT2":["Azores","AF"],
        "CT3":["Madeira Is","AF"],
        "CT9":["Madeira Is","AF"],
        "CU":["Azores Is","AF"],
        "CV":["Uruguay","SA"],
        "CW":["Uruguay","SA"],
        "CX":["Uruguay ","SA"],
        "CY":["Canada","NA"],
        "CZ":["Canada","NA"],
        "D2":["Angola","AF"],
        "D3":["Angola","AF"],
        "D4":["Cape Verde",""],
        "D6":["Comoros",""],
        "D7":["South Korea","AS"],
        "D8":["South Korea","AS"],
        "D9":["South Korea","AS"],
        "DA":["Germany","EU"],
        "DB":["Germany","EU"],
        "DC":["Germany","EU"],
        "DD":["Germany","EU"],
        "DE":["Germany","EU"],
        "DF":["Germany","EU"],
        "DG":["Germany","EU"],
        "DH":["Germany","EU"],
        "DI":["Germany","EU"],
        "DJ":["Germany","EU"],
        "DK":["Germany","EU"],
        "DL":["Germany","EU"],
        "DM":["Germany","EU"],
        "DN":["Germany","EU"],
        "DO":["Germany","EU"],
        "DP":["Germany","EU"],
        "DQ":["Germany","EU"],
        "DR":["Germany","EU"],
        "DS":["South Korea","AS"],
        "DT":["South Korea","AS"],
        "DU":["Philippines","AS"],
        "DV":["Philippines","AS"],
        "DX":["Philippines","AS"],
        "DY":["Philippines","AS"],
        "DZ":["Philippines","AS"],
        "E2":["Thailand","AS"],
        "E3":["Eritrea","AS"],
        "E4":["Palestina","AS"],
        "E5":["North Cook Is","AS"],
        "EA":["Spain","EU"],
        "EA6":["Balearic Is","EU"],
        "EA8":["Canary Is","AF"],
        "EA9":["Ceuta","AF"],
        "EB":["Spain","EU"],
        "EB6":["Balearic Is","EU"],
        "EB8":["Canary Is","AF"],
        "EB9":["Ceuta","AF"],
        "EC":["Spain","EU"],
        "EC6":["Balearic Is","EU"],
        "EC8":["Canary Is",""],
        "EC9":["Ceuta",""],
        "EC9":["Melilla",""],
        "ED":["Spain","EU"],
        "ED6":["Balearic Is","EU"],
        "ED8":["Canary Is",""],
        "ED9":["Ceuta",""],
        "ED9":["Melilla",""],
        "EE":["Spain","EU"],
        "EE6":["Balearic Is","EU"],
        "EE8":["Canary Is",""],
        "EE9":["Ceuta",""],
        "EF":["Spain","EU"],
        "EF6":["Balearic Is","EU"],
        "EF8":["Canary Is",""],
        "EF9":["Ceuta",""],
        "EG":["Spain","EU"],
        "EG6":["Balearic Is","EU"],
        "EG8":["Canary Is",""],
        "EG9":["Ceuta",""],
        "EH":["Spain","EU"],
        "EH6":["Balearic Is","EU"],
        "EH8":["Canary Is",""],
        "EH9":["Ceuta",""],
        "EI":["Ireland","EU"],
        "EJ":["Ireland","EU"],
        "EK":["Armenia",""],
        "EL":["Liberia",""],
        "EM":["Ukraine","EU"],
        "EN":["Ukraine","EU"],
        "EO":["Ukraine","EU"],
        "EP":["Iran","AS"],
        "EQ":["Iran","AS"],
        "ER":["Moldova","EU"],
        "ES":["Estonia","EU"],
        "ET":["Ethiopia",""],
        "EU":["Belarus","EU"],
        "EV":["Belarus","EU"],
        "EW":["Belarus","EU"],
        "EX":["Kyrgyzstan","AS"],
        "EY":["Tadjikistan","AS"],
        "EZ":["Turkmenistan","AS"],
        "F1":["France","EU"],
        "F2":["France","EU"],
        "F3":["France","EU"],
        "F4":["France","EU"],
        "F5":["France","EU"],
        "F6":["France","EU"],
        "F7":["France","EU"],
        "F8":["France","EU"],
        "F9":["France","EU"],
        "FB":["France","EU"],
        "FC":["France Corsica","EU"],
        "FD":["France","EU"],
        "FE":["France","EU"],
        "FF":["France","EU"],
        "FG":["France Guadeloupe",""],
        "FH":["France Mayotte",""],
        "FJ":["France St Martin",""],
        "FK":["France New Caledonia",""],
        "FM":["France Martinique",""],
        "FO":["France Clipperton",""],
        "FO":["France Tahiti",""],
        "FO/C":["Clipperton",""],
        "FP":["France St Pierre Miquelon",""],
        "FR":["Glorioso",""],
        "FR":["Juan De Nova",""],
        "FR":["Reunion","AF"],
        "FR":["Tromelin",""],
        "FR/G":["Glorioso",""],
        "FR/J":["Juan De Nova",""],
        "FR/T":["Tromelin",""],
        "FS":["France St Martin",""],
        "FT0W":["Crozet",""],
        "FT0X":["Kerguelen Is",""],
        "FT0Z":["Amsterdam Paul",""],
        "FT2W":["Crozet",""],
        "FT2X":["Kerguelen Is",""],
        "FT2Z":["Amsterdam Paul",""],
        "FT5W":["Crozet",""],
        "FT5X":["Kerguelen Is",""],
        "FT5Z":["Amsterdam Paul",""],
        "FT8W":["Crozet",""],
        "FT8X":["Kerguelen Is",""],
        "FT8Y":["Antarctica","AN"],
        "FT8Z":["Amsterdam Paul",""],
        "FU":["France","EU"],
        "FV":["France","EU"],
        "FW":["Wallis Is","EU"],
        "FX":["France","EU"],
        "FY":["France French Guiana",""],
        "G0":["GB England","EU"],
        "G1":["GB England","EU"],
        "G2":["GB England","EU"],
        "G3":["GB England","EU"],
        "G4":["GB England","EU"],
        "G5":["GB England","EU"],
        "G6":["GB England","EU"],
        "G7":["GB England","EU"],
        "G8":["GB England","EU"],
        "G9":["GB England","EU"],
        "G":["GB England","EU"],
        "GB":["GB","EU"],
        "GC":["GB Wales","EU"],
        "GD":["GB Isle of Man","EU"],
        "GH":["GB Jersey","EU"],
        "GI":["Northern Ireland","EU"],
        "GJ":["GB Jersey","EU"],
        "GM":["Scotland","EU"],
        "GN":["Northern Ireland","EU"],
        "GP":["GB Guernsey & Dependencies","EU"],
        "GS":["Scotland","EU"],
        "GT":["GB Isle of Man","EU"],
        "GU":["GB Guernsey & Dependencies","EU"],
        "GW":["GB Wales","EU"],
        "GX":["GB England","EU"],
        "H2":["Cyprus","EU"],
        "H3":["Panama","SA"],
        "H4":["Solomon Is",""],
        "H5":["So Africa","AF"],
        "H6":["Nicaragua","SA"],
        "H7":["Nicaragua","SA"],
        "H8":["Panama","SA"],
        "H9":["Panama","SA"],
        "HA":["Hungary","EU"],
        "HB":["Switzerland","EU"],
        "HB0":["Liechtenstein","EU"],
        "HC":["Ecuador","SA"],
        "HC8":["Galapagos",""],
        "HD":["Ecuador","SA"],
        "HD8":["Galapagos",""],
        "HE":["Switzerland","EU"],
        "HF":["Poland","EU"],
        "HF0":["So Shetland",""],
        "HG":["Hungary","EU"],
        "HH":["Haiti",""],
        "HI":["Dominican Rep",""],
        "HJ":["Columbia","SA"],
        "HK":["Colombia","SA"],
        "HK0":["Malpelo Is",""],
        "HK0":["San Andres Is",""],
        "HK0/A":["San Andres Is",""],
        "HK0/M":["Malpelo Is",""],
        "HL":["South Korea","AS"],
        "HM":["North Korea","AS"],
        "HN":["Iraq","AS"],
        "HO":["Panama","SA"],
        "HP":["Panama","SA"],
        "HQ":["Honduras","SA"],
        "HR":["Honduras","SA"],
        "HS":["Thailand","AS"],
        "HT":["Nicaragua","SA"],
        "HU":["El Salvador","SA"],
        "HV":["Vatican City","EU"],
        "HW":["France","EU"],
        "HX":["France","EU"],
        "HY":["France","EU"],
        "HZ":["Saudi Arabia","AS"],
        "I0":["Italy","EU"],
        "I1":["Italy","EU"],
        "I2":["Italy","EU"],
        "I3":["Italy","EU"],
        "I4":["Italy","EU"],
        "I5":["Italy","EU"],
        "I6":["Italy","EU"],
        "I7":["Italy","EU"],
        "I8":["Italy","EU"],
        "I9":["Italy","EU"],
        "I":["Italy","EU"],
        "IA":["Italy","EU"],
        "IB":["Italy","EU"],
        "IC":["Italy","EU"],
        "ID":["Italy","EU"],
        "IE":["Italy","EU"],
        "IF":["Italy","EU"],
        "IG":["Italy","EU"],
        "IH":["Italy","EU"],
        "II":["Italy","EU"],
        "IJ":["Italy","EU"],
        "IK":["Italy","EU"],
        "IL":["Italy","EU"],
        "IM":["Italy","EU"],
        "IN":["Italy","EU"],
        "IO":["Italy","EU"],
        "IP":["Italy","EU"],
        "IQ":["Italy","EU"],
        "IR":["Italy","EU"],
        "IS":["Sardinia","EU"],
        "IT":["Sicily","EU"],
        "IU":["Italy","EU"],
        "IV":["Italy","EU"],
        "IW":["Italy","EU"],
        "IX":["Italy","EU"],
        "IY":["Italy","EU"],
        "IZ":["Italy","EU"],
        "J2":["Djibouti",""],
        "J2/A":["Abu Ail",""],
        "J3":["Grenada",""],
        "J4":["Greece","EU"],
        "J45":["Dodecanese",""],
        "J49":["Crete","EU"],
        "J5":["Guinea Bissau",""],
        "J6":["St Lucia",""],
        "J7":["Dominica",""],
        "J8":["St Vincent",""],
        "JA":["Japan","AS"],
        "JB":["Japan","AS"],
        "JC":["Japan","AS"],
        "JD":["Minami Torishima",""],
        "JD":["Ogasawara ",""],
        "JD/O":["Ogasawara",""],
        "JE":["Japan","AS"],
        "JF":["Japan","AS"],
        "JG":["Japan","AS"],
        "JH":["Japan","AS"],
        "JI":["Japan","AS"],
        "JJ":["Japan","AS"],
        "JK":["Japan","AS"],
        "JL":["Japan","AS"],
        "JM":["Japan","AS"],
        "JN":["Japan","AS"],
        "JO":["Japan","AS"],
        "JP":["Japan","AS"],
        "JQ":["Japan","AS"],
        "JR":["Japan","AS"],
        "JS":["Japan","AS"],
        "JT":["Mongolia ","AS"],
        "JU":["Mongolia","AS"],
        "JV":["Mongolia","AS"],
        "JW":["Svalbard Is NO","EU"],
        "JX":["Jan Mayen","EU"],
        "JY":["Jordan","AS"],
        "K0":["USA","NA"],
        "K1":["USA","NA"],
        "K2":["USA","NA"],
        "K3":["USA","NA"],
        "K4":["USA","NA"],
        "K5":["USA","NA"],
        "K6":["USA","NA"],
        "K7":["USA","NA"],
        "K8":["USA","NA"],
        "K9":["USA","NA"],
        "KA":["USA","NA"],
        "KB":["USA","NA"],
        "KC":["USA","NA"],
        "KD":["USA","NA"],
        "KE":["USA","NA"],
        "KF":["USA","NA"],
        "KG":["USA","NA"],
        "KH":["USA","NA"],
        "KI":["USA","NA"],
        "KJ":["USA","NA"],
        "KK":["USA","NA"],
        "KL":["USA  Alaska","NA"],
        "KM":["USA","NA"],
        "KN":["USA","NA"],
        "KO":["USA","NA"],
        "KP":["USA","NA"],
        "KQ":["USA","NA"],
        "KR":["USA","NA"],
        "KS":["USA","NA"],
        "KT":["USA","NA"],
        "KU":["USA","NA"],
        "KV":["USA","NA"],
        "KW":["USA","NA"],
        "KX":["USA","NA"],
        "KY":["USA","NA"],
        "KZ":["USA","NA"],
        "KA-KZ":["USA","NA"],
        "KC4":["Antarctica Bryd","AN"],
        "KC4":["Antarctica McMurdo","AN"],
        "KC4":["Antarctica Palmer","AN"],
        "KC6":["East Carolines",""],
        "KC6":["West Carolines",""],
        "KC6/E":["East Caroline",""],
        "KC6/W":["West Carolines",""],
        "KG4":["USA OR Guantanamo Bay",""],
        "KG6":["Guam",""],
        "KH0":["Mariana Is",""],
        "KH1":["Baker Howland",""],
        "KH2":["Guam",""],
        "KH3":["Johnston Is",""],
        "KH4":["Midway Is",""],
        "KH5":["Palmyra Is",""],
        "KH5K":["Kingman Reef",""],
        "KH6":["Hawaii",""],
        "KH6":["Hawaii",""],
        "KH7":["Kure Is",""],
        "KH7K":["Kure Is",""],
        "KH8":["American Samoa",""],
        "KH9":["Wake Is",""],
        "KL":["Alaska","NA"],
        "KP":["USA Caribian Is","SA"],
        "KP1":["Navassa Is",""],
        "KP2":["Virgin Is",""],
        "KP3":["Puerto Rico",""],
        "KP4":["Puerto Rico",""],
        "KP5":["Desecheo Is",""],
        "KV4":["Virgin Is",""],
        "L1":["Argentina","SA"],
        "L2":["Argentina","SA"],
        "L3":["Argentina","SA"],
        "L4":["Argentina","SA"],
        "L5":["Argentina","SA"],
        "L6":["Argentina","SA"],
        "L7":["Argentina","SA"],
        "L8":["Argentina","SA"],
        "L9":["Argentina","SA"],
        "LA- LN":["Norway ","EU"],
        "LA":["Norway ","EU"],
        "LB":["Norway ","EU"],
        "LC":["Norway ","EU"],
        "LD":["Norway ","EU"],
        "LE":["Norway ","EU"],
        "LF":["Norway ","EU"],
        "LG":["Norway ","EU"],
        "LH":["Norway ","EU"],
        "LI":["Norway ","EU"],
        "LJ":["Norway ","EU"],
        "LK":["Norway ","EU"],
        "LL":["Norway ","EU"],
        "LM":["Norway ","EU"],
        "LN":["Norway ","EU"],
        "LO":["Argentina","SA"],
        "LP":["Argentina","SA"],
        "LQ":["Argentina","SA"],
        "LR":["Argentina","SA"],
        "LS":["Argentina","SA"],
        "LT":["Argentina","SA"],
        "LU":["Argentina","SA"],
        "LV":["Argentina","SA"],
        "LW":["Argentina","SA"],
        "LX":["Luxembourg","EU"],
        "LY":["Lithuania ","EU"],
        "LZ":["Bulgaria","EU"],
        "M1":["San Marino","EU"],
        "M":["England","EU"],
        "MC":["Wales (Clubs)","EU"],
        "MD":["Isle of Man","EU"],
        "MH":["Jersey (Clubs)","EU"],
        "MI":["Northern Ireland","EU"],
        "MJ":["Jersey","EU"],
        "MM":["Scotland","EU"],
        "MN":["Northern Ireland (Clubs)","EU"],
        "MP":["Guernsey & Dependencies(Clubs)",""],
        "MS":["Scotland (Clubs)","EU"],
        "MT":["Isle Of Man (Clubs)","EU"],
        "MU":["Guernsey & Dependencies","EU"],
        "MW":["Wales","EU"],
        "MX":["England (Clubs)","EU"],
        "N0":["USA","NA"],
        "N1":["USA","NA"],
        "N2":["USA","NA"],
        "N3":["USA","NA"],
        "N4":["USA","NA"],
        "N5":["USA","NA"],
        "N6":["USA","NA"],
        "N7":["USA","NA"],
        "N8":["USA","NA"],
        "N9":["USA","NA"],
        "NA":["USA","NA"],
        "NB":["USA","NA"],
        "NC":["USA","NA"],
        "ND":["USA","NA"],
        "NE":["USA","NA"],
        "NF":["USA","NA"],
        "NG":["USA","NA"],
        "NH":["USA","NA"],
        "NI":["USA","NA"],
        "NJ":["USA","NA"],
        "NK":["USA","NA"],
        "NL":["USA Alaska","NA"],
        "NM":["USA","NA"],
        "NN":["USA","NA"],
        "NO":["USA","NA"],
        "NP":["USA","NA"],
        "NQ":["USA","NA"],
        "NR":["USA","NA"],
        "NS":["USA","NA"],
        "NT":["USA","NA"],
        "NU":["USA","NA"],
        "NV":["USA","NA"],
        "NW":["USA","NA"],
        "NX":["USA","NA"],
        "NY":["USA","NA"],
        "NZ":["USA","NA"],
        "NC6":["Eastern Carolines",""],
        "NC6":["Western Carolines",""],
        "NH0":["Mariana Is",""],
        "NH1":["Baker Howland",""],
        "NH2":["Guam",""],
        "NH3":["Johnston Is",""],
        "NH4":["Midway Is",""],
        "NH5":["Palmyra Is",""],
        "NH5K":["Kingman Reef",""],
        "NH6":["Hawaii",""],
        "NH6":["Hawaii",""],
        "NH7K":["Kure Is",""],
        "NH8":["American Samoa",""],
        "NH9":["Wake Is",""],
        "NL":["Alaska",""],
        "NP":["USA Caribian Is","SA"],
        "NP1":["Navassa Is","SA"],
        "NP2":["Virgin Is","SA"],
        "NP3":["Puerto Rico","SA"],
        "NP4":["Puerto Rico","SA"],
        "NP5":["Desecheo Is","SA"],
        "OA":["Peru","SA"],
        "OB":["Peru","SA"],
        "OC":["Peru","SA"],
        "OD":["Lebanon","AS"],
        "OE":["Austria","EU"],
        "OF":["Finland","EU"],
        "OF0":["Aland Is","EU"],
        "OG":["Finland","EU"],
        "OG0":["Aland Is","EU"],
        "OH":["Finland","EU"],
        "OH0":["Aland Is","EU"],
        "OH0M":["Market Reef ","EU"],
        "OI":["Finland","EU"],
        "OJ0":["Market Reef ","EU"],
        "OK":["Czech Republic","EU"],
        "OL":["Czech Republic","EU"],
        "OM":["Slovakia","EU"],
        "ON":["Belgium ","EU"],
        "OO":["Belgium","EU"],
        "OP":["Belgium","EU"],
        "OQ":["Belgium","EU"],
        "OR":["Belgium","EU"],
        "OS":["Belgium","EU"],
        "OT":["Belgium","EU"],
        "OV":["Denmark","EU"],
        "OX":["Greenland",""],
        "OY":["Faroe Is",""],
        "OZ":["Denmark","EU"],
        "P2":["Papua",""],
        "P3":["Cyprus","EU"],
        "P30":["Cyprus","EU"],
        "P36":["Cyprus","EU"],
        "P4":["Aruba",""],
        "P5":["North Korea","AS"],
        "P6":["North Korea","AS"],
        "P7":["North Korea","AS"],
        "P8":["North Korea","AS"],
        "P9":["North Korea","AS"],
        "PA":["Netherlands","EU"],
        "PB":["Netherlands","EU"],
        "PC":["Netherlands","EU"],
        "PD":["Netherlands","EU"],
        "PE":["Netherlands","EU"],
        "PF":["Netherlands","EU"],
        "PG":["Netherlands","EU"],
        "PH":["Netherlands","EU"],
        "PI":["Netherlands","EU"],
        "PJ":["Antilles St Maarten NL","SA"],
        "PJ0":["Neth Antilles","SA"],
        "PJ1":["Neth Antilles","SA"],
        "PJ2":["Neth Antilles","SA"],
        "PJ3":["Neth Antilles","SA"],
        "PJ4":["Neth Antilles","SA"],
        "PJ5":["St Maarten","SA"],
        "PJ7":["St Maarten","SA"],
        "PJ9":["Neth Antilles","SA"],
        "PK":["Indonesia","AS"],
        "PL":["Indonesia","AS"],
        "PM":["Indonesia","AS"],
        "PN":["Indonesia","AS"],
        "PO":["Indonesia","AS"],
        "PP":["Brazil","SA"],
        "PQ":["Brazil","SA"],
        "PQ":["Brazil","SA"],
        "PR":["Brazil","SA"],
        "PS":["Brazil","SA"],
        "PT":["Brazil","SA"],
        "PU":["Brazil","SA"],
        "PY":["Brazil","SA"],
        "PZ":["Suriname",""],
        "R0":["Russia","AS"],
        "R1":["Russia","EU"],
        "R2":["Russia","AS"],
        "R3":["Russia","EU"],
        "R4":["Russia","EU"],
        "R5":["Russia","EU"],
        "R6":["Russia","EU"],
        "R7":["Russia","AS"],
        "R8":["Russia","AS"],
        "R9":["Russia","AS"],
        "RA":["Russia","EU"],
        "RB":["Russia","EU"],
        "RC":["Russia","EU"],
        "RD":["Russia","EU"],
        "RE":["Russia","EU"],
        "RF":["Russia","EU"],
        "RD":["Russia","EU"],
        "RE":["Russia","EU"],
        "RF":["Russia","EU"],
        "RG":["Russia","EU"],
        "RH":["Russia","EU"],
        "RI":["Russia","EU"],
        "RJ":["Russia","EU"],
        "RK":["Russia","EU"],
        "RL":["Russia","EU"],
        "RM":["Russia","EU"],
        "RN":["Russia","EU"],
        "RO":["Russia","EU"],
        "RP":["Russia","EU"],
        "RQ":["Russia","EU"],
        "RR":["Russia","EU"],
        "RS":["Russia","EU"],
        "RT":["Russia","EU"],
        "RU":["Russia","EU"],
        "RV":["Russia","EU"],
        "RW":["Russia","EU"],
        "RX":["Russia","EU"],
        "RY":["Russia","EU"],
        "RZ":["Russia","EU"],
        "S0":["Western Sahara","AF"],
        "S2":["Bangladesh","AS"],
        "S3":["Bangladesh","AS"],
        "S4":["South Africa","AF"],
        "S5":["Slovenia","EU"],
        "S7":["Seychelles",""],
        "S8":["South Africa","AF"],
        "S9":["Sao Tome",""],
        "SA":["Sweden","EU"],
        "SB":["Sweden","EU"],
        "SI":["Sweden","EU"],
        "SJ":["Sweden","EU"],
        "SK":["Sweden","EU"],
        "SL":["Sweden","EU"],
        "SM":["Sweden","EU"],
        "SN":["Poland","EU"],
        "SO":["Poland","EU"],
        "SP":["Poland","EU"],
        "SQ":["Poland","EU"],
        "SR":["Poland","EU"],
        "ST":["Sudan","AF"],
        "ST0":["Southern Sudan","AF"],
        "SU":["Egypt","AF"],
        "SV":["Greece","EU"],
        "SV/A":["Mount Athos","EU"],
        "SV5":["Dodecanese","EU"],
        "SV9":["Crete","EU"],
        "SW":["Greece","EU"],
        "SW5":["Dodecanese","EU"],
        "SW9":["Crete","EU"],
        "SX":["Greece","EU"],
        "SX5":["Dodecanese","EU"],
        "SX9":["Crete","EU"],
        "SY":["Mount Athos","EU"],
        "SZ":["Greece","EU"],
        "T2":["Tuvalu","OZ"],
        "T3":["Banaba Is","OZ"],
        "T3":["Central Kiribati","OZ"],
        "T3":["East Kiribati","OZ"],
        "T3":["West Kiribati","OZ"],
        "T30":["West Kiribati","OZ"],
        "T31":["Central Kiribati","OZ"],
        "T32":["East Kiribati","OZ"],
        "T33":["Banaba Is","OZ"],
        "T4":["Cuba","NA"],
        "T5":["Somalia","AF"],
        "T6":["Afghanistan","AS"],
        "T7":["San Marino","EU"],
        "T8":["So Africa","AF"],
        "T88":["Belau (Palau)(KC6)","OZ"],
        "T9":["Bosnia Herzegovina","EU"],
        "TA":["Turkey","AS"],
        "TD":["Guatemala","SA"],
        "TE":["Costa Rica","SA"],
        "TF":["Iceland","EU"],
        "TG":["Guatemala","SA"],
        "TH":["France","EU"],
        "TI":["Costa Rica","SA"],
        "TI9":["Cocos Is","AS"],
        "TJ":["Cameroon","AF"],
        "TK":["Corsica","EU"],
        "TL":["Central Africa Rep","AF"],
        "TM":["France (Outside France)",""],
        "TN":["Congo","AF"],
        "TO":["France (Outside France)",""],
        "TO5M":["St. Pierre Miquelon (Typical Assignment)",""],
        "TP":["France EU Straßburg","EU"],
        "TQ":["France","EU"],
        "TR":["Gabon","AF"],
        "TT":["Chad","AS"],
        "TU":["Ivory Coast","AF"],
        "TV":["France","EU"],
        "TW":["France","EU"],
        "TX":["Chesterfield Islands FR","OZ"],
        "TY":["Benin","AF"],
        "TZ":["Mali","AF"],
        "U0":["Russia",""],
        "U1":["Russia","EU"],
        "U2":["Russia",""],
        "U3":["Russia","EU"],
        "U4":["Russia","EU"],
        "U5":["Russia","EU"],
        "U6":["Russia","EU"],
        "U7":["Russia","EU"],
        "U8":["Russia","EU"],
        "U9":["Russia","EU"],
        "UA":["Russia","EU"],
        "UB":["Russia","EU"],
        "UC":["Russia","EU"],
        "UD":["Russia","EU"],
        "UE":["Russia","EU"],
        "UF":["Russia","EU"],
        "UG":["Russia","EU"],
        "UH":["Russia","EU"],
        "UI":["Russia","EU"],
        "UJ":["Uzbekistan","AS"],
        "UK":["Uzbekistan","AS"],
        "UL":["Uzbekistan","AS"],
        "UM":["Uzbekistan","AS"],
        "UN":["Kazakhstan","AS"],
        "UO":["Kazakhstan","AS"],
        "UP":["Kazakhstan","AS"],
        "UQ":["Kazakhstan","AS"],
        "UR":["Ukraine","EU"],
        "US":["Ukraine","EU"],
        "UT":["Ukraine","EU"],
        "UU":["Ukraine","EU"],
        "UV":["Ukraine","EU"],
        "UW":["Ukraine","EU"],
        "UX":["Ukraine","EU"],
        "UY":["Ukraine","EU"],
        "UZ":["Ukraine","EU"],
        "V2":["Antigua","NA"],
        "V3":["Belize","NA"],
        "V4":["St Kitts","NA"],
        "V5":["Namibia","AF"],
        "V50":["Namibia","AF"],
        "V51":["Namibia","AF"],
        "V6":["Fed Micronesia","OZ"],
        "V63":["Fed Micronesia","OZ"],
        "V7":["Marshall Is","OZ"],
        "V73":["Marshall Is","OZ"],
        "V8":["Brunei","AS"],
        "V85":["Brunei","AS"],
        "VA":["Canada","NA"],
        "VB":["Canada","NA"],
        "VC":["Canada","NA"],
        "VD":["Canada","NA"],
        "VE":["Canada","NA"],
        "VF":["Canada","NA"],
        "VG":["Canada","NA"],
        "VH":["Australia","AU"],
        "VI":["Australia","AU"],
        "VJ":["Australia","AU"],
        "VK":["Australia","AU"],
        "VK0":["Heard & Macquarie Is","AU"],
        "VK1":["Australia","AU"],
        "VK2":["Australia","AU"],
        "VK3":["Australia","AU"],
        "VK4":["Australia","AU"],
        "VK5":["Australia","AU"],
        "VK6":["Australia","AU"],
        "VK7":["Australia","AU"],
        "VK8":["Australia","AU"],
        "VK9":["Australia","AU"],
        "VL":["Australia","AU"],
        "VM":["Australia","AU"],
        "VN":["Australia","AU"],
        "VO":["Canada","NA"],
        "VP8":["GB Islands ","AN"],
        "VP8ADE":["Adelaide Is. GB","AN"],
        "VP8VHF":["Falkland Is. GB","SA"],
        "VQ":["GB Chagos","AS"],
        "VR":["China","AS"],
        "VR2":["Hong Kong","AS"],
        "VR6":["China","AS"],
        "VS6":["Hong Kong","AS"],
        "VT":["India","AS"],
        "VU":["India","AS"],
        "VU4":["Andaman Is","AS"],
        "VU7":["Laccadive Is","AS"],
        "VV":["India","AS"],
        "VW":["India","AS"],
        "VX":["Canada","NA"],
        "VY":["Canada","NA"],
        "VZ":["Australia","AU"],
        "W0":["USA","NA"],
        "W1":["USA","NA"],
        "W2":["USA","NA"],
        "W3":["USA","NA"],
        "W4":["USA","NA"],
        "W5":["USA","NA"],
        "W6":["USA","NA"],
        "W7":["USA","NA"],
        "W8":["USA","NA"],
        "W9":["USA","NA"],
        "WA":["USA","NA"],
        "WB":["USA","NA"],
        "WC":["USA","NA"],
        "WD":["USA","NA"],
        "WE":["USA","NA"],
        "WF":["USA","NA"],
        "WG":["USA","NA"],
        "WH":["USA","NA"],
        "WI":["USA","NA"],
        "WJ":["USA","NA"],
        "WK":["USA","NA"],
        "WL":["USA","NA"],
        "WM":["USA","NA"],
        "WN":["USA","NA"],
        "WO":["USA","NA"],
        "WP":["USA","NA"],
        "WQ":["USA","NA"],
        "WR":["USA","NA"],
        "WR":["USA","NA"],
        "WS":["USA","NA"],
        "WT":["USA","NA"],
        "WU":["USA","NA"],
        "WV":["USA","NA"],
        "WW":["USA","NA"],
        "WX":["USA","NA"],
        "WY":["USA","NA"],
        "WZ":["USA","NA"],
        "WL":["Alaska","NA"],
        "X5":["Bosnia Herzegovina (Unofficial???)","EU"],
        "XA":["Mexico","NA"],
        "XB":["Mexico","NA"],
        "XC":["Mexico","NA"],
        "XD":["Mexico","NA"],
        "XE":["Mexico","NA"],
        "XF":["Mexico","NA"],
        "XG":["Mexico","NA"],
        "XH":["Mexico","NA"],
        "XJ":["Canada","NA"],
        "XK":["Canada","NA"],
        "XL":["Canada","NA"],
        "XM":["Canada","NA"],
        "XN":["Canada","NA"],
        "XO":["Canada","NA"],
        "XP":["Denmark","EU"],
        "XQ":["Chile","SA"],
        "XR":["Chile","SA"],
        "XS":["China","AS"],
        "XT":["Burkina Faso","AS"],
        "XU":["Kampuchea","AS"],
        "XV":["Vietnam","AS"],
        "XW":["Laos","AS"],
        "XX":["Macao","AS"],
        "XY":["Burma","AS"],
        "XZ":["Burma","AS"],
        "Y2":["Germany","EU"],
        "Y3":["Germany","EU"],
        "Y4":["Germany","EU"],
        "Y5":["Germany","EU"],
        "Y6":["Germany","EU"],
        "Y7":["Germany","EU"],
        "Y8":["Germany","EU"],
        "Y9":["Germany","EU"],
        "Y90":["Antarctica","AN"],
        "YA":["Afghanistan","AS"],
        "YB":["Indonesia","AS"],
        "YC":["Indonesia","AS"],
        "YD":["Indonesia","AS"],
        "YE":["Indonesia","AS"],
        "YF":["Indonesia","AS"],
        "YG":["Indonesia","AS"],
        "YH":["Indonesia","AS"],
        "YI":["Iraq","AS"],
        "YJ":["Vanuatu","AS"],
        "YK":["Syria","AS"],
        "YL":["Latvia","AS"],
        "YM":["Turkey","AS"],
        "YN":["Nicaragua","SA"],
        "YO":["Romania","EU"],
        "YP":["Romania","EU"],
        "YQ":["Romania","EU"],
        "YR":["Romania","EU"],
        "YS":["El Salvador","SA"],
        "YT":["Yugoslavia","EU"],
        "YT1":["Yugoslavia","EU"],
        "YT4":["Bosnia Herzegovina","EU"],
        "YT5":["Macedonia","EU"],
        "YT6":["Yugoslavia","EU"],
        "YT7":["Yugoslavia","EU"],
        "YT8":["Yugoslavia","EU"],
        "YU":["Yugoslavia","EU"],
        "YU1":["Yugoslavia","EU"],
        "YU4":["Bosnia Herzegovina","EU"],
        "YU5":["Macedonia","EU"],
        "YU6":["Yugoslavia","EU"],
        "YU7":["Yugoslavia","EU"],
        "YU8":["Yugoslavia","EU"],
        "YV":["Venezuela","SA"],
        "YV0":["Aves Is","So"],
        "YW":["Venezuela","Mo"],
        "YX":["Venezuela","Di"],
        "YX0":["Aves Is","Mi"],
        "YY":["Venezuela","Do"],
        "YZ":["Yugoslavia","EU"],
        "YZ4":["Bosnia Herzegovina","EU"],
        "YZ5":["Macedonia","EU"],
        "Z2":["Zimbabwe","AF"],
        "Z3":["Macedonia","EU"],
        "ZA":["Albania","EU"],
        "ZB":["Gibraltar","EU"],
        "ZC4":["UK Soverign Base",""],
        "ZD7":["St Helena GB","AF"],
        "ZD8":["Ascension Is GB","AF"],
        "ZD9":["Tristan Da Cunha GB","AF"],
        "ZE":["Zimbabwe","AF"],
        "ZF":["Cayman Is",""],
        "ZK1/N":["No Cook Is",""],
        "ZK1/S":["So Cook Is",""],
        "ZK2":["Niue Is",""],
        "ZK3":["Tokelaus",""],
        "ZL1":["New Zealand","OZ"],
        "ZL2":["New Zealand","OZ"],
        "ZL3":["New Zealand","OZ"],
        "ZL6":["New Zealand","OZ"],
        "ZL0":["Antarctica Scott (AU)","AN"],
        "ZL5":["Antarctica Scott (AU)","AN"],
        "ZL7":["Chatham Is","AU"],
        "ZL8":["Kermadec Is","AU"],
        "ZL9":["Auckland Campbell","AU"],
        "ZL":["New Zealand","OZ"],
        "ZM":["New Zealand","AU"],
        "ZM7":["Chatham Is","AU"],
        "ZM8":["Kermadec Is","AU"],
        "ZM9":["Auckland Campbell","AU"],
        "ZP":["Paraguay","SA"],
        "ZS":["So Africa","AF"],
        "ZS2":["Marion Is","AF"],
        "ZS3":["Namibia","AF"],
        "ZS8":["Marion Is","AF"],
        "ZS9":["Walvis Bay","AF"],
        "ZU":["So Africa","AF"],
        "ZV":["Brazil","SA"],
        "ZW":["Brazil","SA"],
        "ZX":["Brazil","SA"],
        "ZX0F":["Fer De Noronha",""],
        "ZX0S":["Peter Paul Rocks",""],
        "ZX0T":["Trindade",""],
        "ZY":["Brazil","SA"],
        "ZY0F":["Fer De Noronha",""],
        "ZY0S":["Peter Paul Rocks",""],
        "ZY0T":["Trindade",""],
        "ZZ":["Brazil","SA"],
        "ZZ0F":["Fer De Noronha",""],
        "ZZ0S":["Peter Paul Rocks",""],
        "ZZ0T":["Trindade",""]
        }
        
        # Check Mode
        if dbMode == "overwrite":
            print ("overwrite")
            curs.execute("DROP TABLE IF EXISTS stations")
            curs.execute("CREATE TABLE stations (freq integer, station text, locator text, country text, continent text )")
        
        if dbMode == "append":
            # nothing to do
            print ("append")
        
        # Read Data
        for line in fobjFileIn:
            line = line.strip()
            
            # Check if at least first 4 characters are letters or numbers
            # If numbers we can assume it is frequency information and a valid line examine further
            line1 = line[0:4]
            if line1.isdigit():
                strFreq = line[0:8].strip()
                # in case instead of "." is "," or ";" assume it should be a dot.
                strFreq = Beacons.re.sub(r"[,;]",".",strFreq)
                # Check if frequency has Hertz value, to see by a Dot in the string.
                # If true split it.
                if strFreq.count("."):
                    (strFreqK, strFreqH) = strFreq.split(".")
                    # Check if there is a letter included in Hertz value, eliminate it.
                    strFreqH = Beacons.re.sub(r"[^0-9]","",strFreqH)
                    # Check length of decimals, we need finally 3
                    #  if 1 add 2 zeros, if 2 add 1 zero.
                    if len(strFreqH) == 1:
                        strFreqH = strFreqH + "00"
                    if len(strFreqH) == 2:
                        strFreqH = strFreqH + "0"
                else:
                    strFreqK = strFreq
                    strFreqH = "000"            
                # Check if there is a letter included in KiloHertz value, eliminate it.    
                strFreqK = Beacons.re.sub(r"[^0-9]","",strFreqK)
                strFreq = strFreqK + strFreqH
                intFreq = int(strFreq)
                
                # Extract Call sign
                strStation = line[8:16].strip()
                if strStation.find("WSPR") != -1:
                    continue

                # Extract prefix from Call to get country information from dictionary
                strCoHelp = strStation[:2].strip()
                if (strCoHelp in dicCountry):
                    (strCountry, strCont) = dicCountry[strCoHelp]
                    if strCont =="":
                        strCont = "undef"
                else:
                    strCountry = "undef"
                    strCont = "undef"
                
                # Extract Locator
                strLoc = line[31:37].strip()

                # DB Insert
                curs.execute("INSERT INTO stations VALUES (?, ?, ?, ?, ?);", (intFreq, strStation, strLoc, strCountry, strCont))
                strData = str(intFreq) + ";" + strStation + ";" + strCoHelp + ";" + strLoc + ";" + strCountry + ";" + strCont + "\n"
                print(strData)
                fobjFileOut.write(strData)
        
        # Commit and close DB
        conn.commit()
        conn.close()
        # Close
        fobjFileIn.close()
        
        return
